name: screening_data_processing
channels:
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - python>=3.3
  - matplotlib
  - numpy
  - pandas
  - patsy
  - scipy
  - seaborn
  - statsmodels
  - tqdm
  - ipykernel
  - sklearn

